# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-cf810302-d49d-40d9-a60e-ae1091cf7142";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cf810302-d49d-40d9-a60e-ae1091cf7142".device = "/dev/disk/by-uuid/cf810302-d49d-40d9-a60e-ae1091cf7142";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/23C9-C413";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d5e498c1-4a23-476b-ac9c-61297e991ae2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
