keys:
  - &lonnix_pc age1gzhlc3juamw8g8l6van2smk30473jzrprl97uc5ydl0j0mulaywqtz6etv
  - &lonnix_pi age1gd08l9xcfqmh747qeq5cvhm78py3th66duqullfrf8f832r0z42qn6gz2e
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *lonnix_pc
        - *lonnix_pi
